# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Chomp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from help_window_ui import Ui_helpWIndow

class Ui_mainMenuWindow(object):
    def __init__(self):
        super()
        # initialize default settings
        self.player1_name = 'Użytkownik'
        self.player2_name = 'AlphaBeta'
        self.width = 4
        self.height = 4
        # default list of buttons that function as chocolate pieces
        self.buttonList = [[0] * self.width for _ in range(self.height)]

    def setupUi(self, mainMenuWindow):
        mainMenuWindow.setObjectName("mainMenuWindow")
        mainMenuWindow.setEnabled(True)
        mainMenuWindow.resize(850, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainMenuWindow.sizePolicy().hasHeightForWidth())
        mainMenuWindow.setSizePolicy(sizePolicy)
        mainMenuWindow.setMinimumSize(QtCore.QSize(850, 600))
        mainMenuWindow.setMaximumSize(QtCore.QSize(850, 600))
        mainMenuWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.5625, x2:1, y2:0.545, stop:0 rgba(0, 152, 137, 255), stop:1 rgba(71, 175, 88, 255));")
        mainMenuWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(mainMenuWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 831, 581))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.menuPage = QtWidgets.QWidget()
        self.menuPage.setObjectName("menuPage")
        self.layoutWidget = QtWidgets.QWidget(self.menuPage)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 160, 341, 364))
        self.layoutWidget.setObjectName("layoutWidget")
        self.mainButtons = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.mainButtons.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.mainButtons.setContentsMargins(0, 0, 0, 0)
        self.mainButtons.setObjectName("mainButtons")
        self.startButton = QtWidgets.QPushButton(self.layoutWidget)
        self.startButton.setEnabled(True)
        self.startButton.setMinimumSize(QtCore.QSize(100, 75))
        self.startButton.setStyleSheet("background-color: rgb(122, 75, 52);\n"
"font: 75 20pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.startButton.setText("Graj")
        self.startButton.setIconSize(QtCore.QSize(20, 20))
        self.startButton.setCheckable(False)
        self.startButton.setChecked(False)
        self.startButton.setObjectName("startButton")
        self.mainButtons.addWidget(self.startButton)
        self.settingsButton = QtWidgets.QPushButton(self.layoutWidget)
        self.settingsButton.setMinimumSize(QtCore.QSize(0, 75))
        self.settingsButton.setStyleSheet("background-color: rgb(122, 75, 52);\n"
"font: 75 20pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.settingsButton.setText("Ustawienia")
        self.settingsButton.setIconSize(QtCore.QSize(20, 20))
        self.settingsButton.setCheckable(False)
        self.settingsButton.setChecked(False)
        self.settingsButton.setObjectName("settingsButton")
        self.mainButtons.addWidget(self.settingsButton)
        self.authorsButton = QtWidgets.QPushButton(self.layoutWidget)
        self.authorsButton.setMinimumSize(QtCore.QSize(0, 75))
        self.authorsButton.setStyleSheet("background-color: rgb(122, 75, 52);\n"
"font: 75 20pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.authorsButton.setText("Autorzy")
        self.authorsButton.setIconSize(QtCore.QSize(20, 20))
        self.authorsButton.setCheckable(False)
        self.authorsButton.setChecked(False)
        self.authorsButton.setObjectName("authorsButton")
        self.mainButtons.addWidget(self.authorsButton)
        self.helpButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButton.sizePolicy().hasHeightForWidth())
        self.helpButton.setSizePolicy(sizePolicy)
        self.helpButton.setMinimumSize(QtCore.QSize(0, 75))
        self.helpButton.setStyleSheet("background-color: rgb(122, 75, 52);\n"
"font: 75 20pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.helpButton.setText("Pomoc")
        self.helpButton.setIconSize(QtCore.QSize(20, 20))
        self.helpButton.setCheckable(False)
        self.helpButton.setChecked(False)
        self.helpButton.setObjectName("helpButton")
        self.mainButtons.addWidget(self.helpButton)
        self.mainTitle = QtWidgets.QLabel(self.menuPage)
        self.mainTitle.setGeometry(QtCore.QRect(120, 30, 261, 111))
        self.mainTitle.setMaximumSize(QtCore.QSize(661, 16777215))
        self.mainTitle.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"font: 87 36pt \"Arial Black\";\n"
"color: rgb(122, 75, 52)\n"
"")
        self.mainTitle.setObjectName("mainTitle")
        self.label_4 = QtWidgets.QLabel(self.menuPage)
        self.label_4.setGeometry(QtCore.QRect(580, 90, 201, 401))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Chomp/menu_chocolate.png"))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.menuPage)
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.mainTitle_2 = QtWidgets.QLabel(self.settingsPage)
        self.mainTitle_2.setGeometry(QtCore.QRect(70, 20, 401, 111))
        self.mainTitle_2.setMaximumSize(QtCore.QSize(661, 16777215))
        self.mainTitle_2.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"font: 87 36pt \"Arial Black\";\n"
"color: rgb(122, 75, 52)\n"
"")
        self.mainTitle_2.setObjectName("mainTitle_2")
        self.label = QtWidgets.QLabel(self.settingsPage)
        self.label.setGeometry(QtCore.QRect(580, 90, 201, 401))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Chomp/menu_chocolate.png"))
        self.label.setObjectName("label")
        self.layoutWidget1 = QtWidgets.QWidget(self.settingsPage)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 130, 401, 341))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"font: 87 16pt \"Arial Black\";\n"
"color: rgb(122, 75, 52)")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widthSpinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.widthSpinBox.setStyleSheet("font: 87 16pt \"Arial Black\";\n"
"color: rgb(0, 0, 0)")
        self.widthSpinBox.setMinimum(2)
        self.widthSpinBox.setMaximum(10)
        self.widthSpinBox.setProperty("value", 4)
        self.widthSpinBox.setObjectName("widthSpinBox")
        self.horizontalLayout.addWidget(self.widthSpinBox)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"font: 87 16pt \"Arial Black\";\n"
"color: rgb(122, 75, 52)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.heightSpinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightSpinBox.sizePolicy().hasHeightForWidth())
        self.heightSpinBox.setSizePolicy(sizePolicy)
        self.heightSpinBox.setMinimumSize(QtCore.QSize(50, 1))
        self.heightSpinBox.setStyleSheet("font: 87 16pt \"Arial Black\";\n"
"color: rgb(0, 0, 0)")
        self.heightSpinBox.setMinimum(2)
        self.heightSpinBox.setMaximum(10)
        self.heightSpinBox.setProperty("value", 4)
        self.heightSpinBox.setObjectName("heightSpinBox")
        self.horizontalLayout.addWidget(self.heightSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"font: 87 16pt \"Arial Black\";\n"
"color: rgb(122, 75, 52)")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 87 16pt \"Arial Black\";\n"
"color: rgb(0, 0, 0)")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"font: 87 16pt \"Arial Black\";\n"
"color: rgb(122, 75, 52)")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 87 16pt \"Arial Black\";\n"
"color: rgb(0, 0, 0)")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.backToMenu = QtWidgets.QPushButton(self.settingsPage)
        self.backToMenu.setGeometry(QtCore.QRect(140, 490, 221, 51))
        self.backToMenu.setStyleSheet("background-color: rgb(122, 75, 52);\n"
"font: 75 12pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.backToMenu.setObjectName("backToMenu")
        self.stackedWidget.addWidget(self.settingsPage)
        self.gamePage = QtWidgets.QWidget()
        self.gamePage.setObjectName("gamePage")
        self.gridLayoutWidget = QtWidgets.QWidget(self.gamePage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 30, 741, 458))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.chocolateLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.chocolateLayout.setContentsMargins(20, 20, 20, 20)
        self.chocolateLayout.setSpacing(20)
        self.chocolateLayout.setObjectName(u"chocolateLayout")






        self.verticalLayoutWidget = QtWidgets.QWidget(self.gamePage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 500, 741, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(450)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.player1Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.player1Label.setStyleSheet("background-color: rgb(122, 75, 52);\n"
                                        "font: 75 20pt \"Arial\";\n"
                                        "color: rgb(255, 255, 0);\n"
                                        "")
        self.player1Label.setFrameShape(QtWidgets.QFrame.Box)
        self.player1Label.setLineWidth(5)
        self.player1Label.setObjectName("player1Label")
        self.horizontalLayout_2.addWidget(self.player1Label)
        self.player2Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.player2Label.setStyleSheet("background-color: rgb(122, 75, 52);\n"
                                        "font: 75 20pt \"Arial\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "border-color: rgb(255, 255, 0);\n"
                                        "")
        self.player2Label.setFrameShape(QtWidgets.QFrame.Box)
        self.player2Label.setLineWidth(5)
        self.player2Label.setObjectName("player2Label")
        self.horizontalLayout_2.addWidget(self.player2Label)
        self.stackedWidget.addWidget(self.gamePage)
        mainMenuWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainMenuWindow)
        self.statusbar.setMouseTracking(False)
        self.statusbar.setObjectName("statusbar")
        mainMenuWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainMenuWindow)

        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainMenuWindow)

        self.setupMainMenu()


    def setupMainMenu(self):
        # go to settings
        self.settingsButton.clicked.connect(lambda x: self.stackedWidget.setCurrentIndex(1))
        # save settings
        self.backToMenu.clicked.connect(self.saveSettings)
        # game start button
        self.startButton.clicked.connect(self.initializeGame)

    def saveSettings(self):
        # get players
        self.player1_name = self.comboBox.currentText()
        self.player2_name = self.comboBox_2.currentText()
        # get chocolate size
        self.width = self.widthSpinBox.value()
        self.height = self.heightSpinBox.value()
        # update space for button list
        self.buttonList = [[0] * self.width for _ in range(self.height)]
        # go back to menu
        self.stackedWidget.setCurrentIndex(0)
        print(f"Setting saved: {(self.player1_name, self.player2_name, self.width, self.height)}")
        _translate = QtCore.QCoreApplication.translate
        self.player1Label.setText(_translate("mainMenuWindow", f"<html><head/><body><p align=\"center\">{self.player1_name}</p></body></html>"))
        self.player2Label.setText(_translate("mainMenuWindow", f"<html><head/><body><p align=\"center\">{self.player2_name}</p></body></html>"))


    def highlight_player(self, player_number: int):
        print("Highlight", player_number)
        if player_number == 1:
            self.player1Label.setStyleSheet("background-color: rgb(122, 75, 52);\n"
                                        "font: 75 20pt \"Arial\";\n"
                                        "color: rgb(255, 255, 0);\n"
                                        "")
            self.player2Label.setStyleSheet("background-color: rgb(122, 75, 52);\n"
                                        "font: 75 20pt \"Arial\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "")
        else:
            self.player1Label.setStyleSheet("background-color: rgb(122, 75, 52);\n"
                                        "font: 75 20pt \"Arial\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "")
            self.player2Label.setStyleSheet("background-color: rgb(122, 75, 52);\n"
                                        "font: 75 20pt \"Arial\";\n"
                                        "color: rgb(255, 255, 0);\n"
                                        "")
    def retranslateUi(self, mainMenuWindow):
        _translate = QtCore.QCoreApplication.translate
        mainMenuWindow.setWindowTitle(_translate("mainMenuWindow", "Chomp"))
        self.mainTitle.setText(_translate("mainMenuWindow", "Chomp"))
        self.mainTitle_2.setText(_translate("mainMenuWindow", "Ustawienia"))
        self.label_3.setText(_translate("mainMenuWindow", "Rozmiar czekolady"))
        self.label_2.setText(_translate("mainMenuWindow", "X"))
        self.label_5.setText(_translate("mainMenuWindow", "Rodzaj gracza 1"))
        self.comboBox.setItemText(0, _translate("mainMenuWindow", "Użytkownik"))
        self.comboBox.setItemText(1, _translate("mainMenuWindow", "AlphaBeta"))
        self.comboBox.setItemText(2, _translate("mainMenuWindow", "MinMax"))
        self.comboBox.setItemText(3, _translate("mainMenuWindow", "Middle"))
        self.comboBox.setItemText(4, _translate("mainMenuWindow", "Random"))
        self.label_6.setText(_translate("mainMenuWindow", "Rodzaj gracza 2"))
        self.comboBox_2.setItemText(0, _translate("mainMenuWindow", "AlphaBeta"))
        self.comboBox_2.setItemText(1, _translate("mainMenuWindow", "Użytkownik"))
        self.comboBox_2.setItemText(2, _translate("mainMenuWindow", "MinMax"))
        self.comboBox_2.setItemText(3, _translate("mainMenuWindow", "Middle"))
        self.comboBox_2.setItemText(4, _translate("mainMenuWindow", "Random"))

        self.backToMenu.setText(_translate("mainMenuWindow", "OK"))
        #TODO patryk to jednak nie działa (nie odsiweza sie)
        self.player1Label.setText(_translate("mainMenuWindow", f"<html><head/><body><p align=\"center\">{self.player1_name}</p></body></html>"))
        self.player2Label.setText(_translate("mainMenuWindow", f"<html><head/><body><p align=\"center\">{self.player2_name}</p></body></html>"))
import chomp_rc
